<h3>测试模块导入展示 按提示安装缺失模块</h3>
经测试 pygeostat包为私有发行包 无法从公共库中安装 
需事先取得CCG(Centre for Computational Geostatistics Knowledge Base)的许可

In [1]:
import pygeostat as gs
import numpy as np
np.set_printoptions(precision=4, suppress=True)
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import os, copy, shutil, sys, glob, time
from mpl_toolkits.axes_grid1 import ImageGrid
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.backends.backend_pdf import PdfPages
from collections import OrderedDict
import numba
from scipy import stats
%matplotlib inline
mpl.style.use("seaborn-ticks")
gs.set_style("ccgpaper", custom={"figure.dpi":150, "savefig.dpi": 150})

ModuleNotFoundError: No module named 'pygeostat'

<h3>展示scikit learn的标准化的相应影响</h3>

In [2]:
import numpy as np
from sklearn.preprocessing import scale
X = np.array([[ 1., -1.,  2.], 
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])
X_scaled = scale(X)
print (X_scaled)
print (X_scaled.mean(axis = 0))
print (X_scaled.std(axis = 0))

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
[0. 0. 0.]
[1. 1. 1.]


In [3]:
X = np.array([[ 1., -1.,  2.], 
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])
X = X + 10000

X_scaled = scale(X)
print (X_scaled)
print (X_scaled.mean(axis = 0))
print (X_scaled.std(axis = 0))

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
[ 0.0000000e+00  0.0000000e+00 -4.8620367e-13]
[1. 1. 1.]


In [4]:
from sklearn.preprocessing import normalize
X = np.array([[ 1., -1.,  2.], 
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])
X_normalized = normalize(X)
print (X_normalized)

[[ 0.40824829 -0.40824829  0.81649658]
 [ 1.          0.          0.        ]
 [ 0.          0.70710678 -0.70710678]]


In [5]:
X = np.array([[ 1., -1.,  2.], 
              [ 2.,  0.,  0.],
              [ 0.,  1., -1.]])
X = X + 10000
X_normalized = normalize(X)
print (X_normalized)

[[0.57736951 0.57725405 0.57742724]
 [0.57742724 0.57731178 0.57731178]
 [0.57735027 0.577408   0.57729253]]


<h3>先标准化 后组合并不会影响结果</h3>

In [8]:
X = np.array([[1.],
              [2.],
              [0.]])
X_scaled = scale(X)
print (X_scaled)

[[ 0.        ]
 [ 1.22474487]
 [-1.22474487]]


In [9]:
X = np.array([[-1.],
              [0.],
              [1.]])
X_scaled = scale(X)
print (X_scaled)

[[-1.22474487]
 [ 0.        ]
 [ 1.22474487]]


<h3>组合方法</h3>

In [12]:
a = np.array([[1], 
              [2]])
b = np.array([[3], 
              [4]])
c = np.array([[5],
              [6]])
np.concatenate((a, b, c), axis=1)

array([[1, 3, 5],
       [2, 4, 6]])

In [19]:
a = np.append([[1], [2]], [[3], [4]], axis = 0)
b = np.append([[1], [2]], [[3], [4]], axis = 1)
print('This is a:\n', a)
print('This is b:\n', b)

This is a:
 [[1]
 [2]
 [3]
 [4]]
This is b:
 [[1 3]
 [2 4]]
